#theme: jekyll-theme-slate
remote_theme: hydecorp/hydejack

title: Birthday Picnic Paw-ty!
description: "Event page for Ada's 5th birthday\n\nJuly 2021"

accent_image: /pics/cover.jpg

theme_color:  rgb(102,212,0)
